Add some missing changes to the ChangeLog
jamulussoftware/jamulus pull request #1177
Opened 2021-03-05 17:19 UTC by softins

2021-03-05 17:27 UTC, hoffie approved these changes
Looks good.

Should we have "coded by" entries? Feel free to merge anyway, I plan to send another PR for Changelog adjustments anyway. :)

2021-03-05 17:29 UTC, hoffie requested changes
Sorry, was a bit quick. Just saw two things which I think could be adapted. :)

2021-03-05 17:29 UTC, hoffie commented on ChangeLog
> +  Compatible with Ubuntu 18 and 20.
```suggestion
  Compatible with Ubuntu 18.04 and 20.04.
```

2021-03-05 17:29 UTC, hoffie commented on ChangeLog
> +- Release now builds .apk installation packages for Android (#880)
```suggestion
- Release now builds experimental .apk installation packages for Android (#880)
```

2021-03-05 23:26 UTC, softins commented
> Looks good.
> 
> Should we have "coded by" entries? Feel free to merge anyway, I plan to send another PR for Changelog adjustments anyway. :)

We should certainly include "coded by" entries for new features, but probably not for bug fixes.

2021-03-05 23:28 UTC, softins commented on ChangeLog
> +- Release now builds .apk installation packages for Android (#880)
Done

2021-03-05 23:28 UTC, softins commented on ChangeLog
> +  Compatible with Ubuntu 18 and 20.
Done

2021-03-05 23:29 UTC, hoffie approved these changes

2021-03-06 10:30 UTC, hoffie approved these changes

2021-03-06 11:06 UTC, ann0see requested changes
The flatpak build has been removed since we're on flathub now. So you could remove it

2021-03-06 11:43 UTC, ann0see approved these changes
Yes, I think we can leave it like that.

2021-03-06 11:44 UTC, merged