Update it.nsi
jamulussoftware/jamulus pull request #1198
Opened 2021-03-07 17:47 UTC by dzpex

2021-03-07 18:31 UTC, ann0see commented on src/res/translation/wininstaller/it.nsi
>       "https://jamulus.io/wiki/Installation-for-Windows#asio"
I think you could link the italian page here too (if it's translated)

2021-03-07 18:45 UTC, ann0see requested changes
- [x] Translator listed in the `src/util.cpp` https://github.com/jamulussoftware/jamulus/blob/387e1125315d1c66be0ae2f6569fdcce99e1974b/src/util.cpp#L503
- [] Looks consistent
- [x] Passes `tools/check-wininstaller-translations.sh` Yes. But it shouldn't since Italian is commented (@hoffie)

Great! Thank you. I think you'll have to uncomment the italian include in installerlng.nsi too.

2021-03-07 21:57 UTC, dzpex commented
ok i make the mods in the installerlng.nsi

2021-03-07 22:02 UTC, ann0see commented
Great! Once the CI is finished, you can test the new installer by downloading the artifacts from the checks page in this PR (will probably take ~ 1h).

2021-03-07 22:04 UTC, ann0see approved these changes
The installer still should be checked. But all in all this looks good.

2021-03-08 08:50 UTC, hoffie approved these changes
Looks good time. Also checked the installer.

@ann0see I will send a PR for the check script.

2021-03-08 08:51 UTC, merged