Advise not to edit service file directly
jamulussoftware/jamulus pull request #1288
Opened 2021-03-17 08:53 UTC by ann0see

Fixes: https://github.com/jamulussoftware/jamulus/issues/1285

You should not change this file since it gets overwritten on updates. It is recommended to use systemctl edit jamulus-headless.service to create a override file. This should contain something like:
```
[Service]

#### See https://jamulus.io/wiki/Command-Line-Options ####
ExecStart=/bin/sh -c '/usr/bin/jamulus-headless -s -n -F -T'
```

2021-03-17 09:25 UTC, hoffie requested changes
I don't think we should comment out `ExecStart`. We could leave it as is.

There would be ways  to make the unit more usable by providing examples for specific flags.

I'm thinking of something like this:
```
#Environment="MULTITHREADING=1"
#Environment="CENTRALSERVER=centralserver.example.org"
# ... repeat for every relevant flag ...
ExecStart=/bin/bash -c '/usr/bin/jamulus-headless -s -n ${MULTITHREADING:+--multithreading} ${CENTRALSERVER:+--centralserver ${CENTRALSERVER}}'
```

That way, users could just put the relevant `Environment=` lines in their overrides and don't have to copy/modify the `ExecStart` line.


However, I'm not sure if this is something which users want and it's worth the effort, but if we wanted to do something like this, it would be the best solution, IMO.

We could also make this generic:

```
#Environment="EXTRA_OPTIONS='--multithreading --centralserver centralserver.foo.example.org'"
ExecStart=/bin/bash -c '/usr/bin/jamulus-headless -s -n ${EXTRA_OPTIONS:-}'
```

This would be a very minimal change and would still support full flexibility with standard command line arguments.

2021-03-17 09:25 UTC, hoffie commented on distributions/debian/jamulus-headless.service
> +#### Change this to publish this server, set genre, location and other parameters. It is recommended to overwrite this file via `systemctl edit jamulus-headless.service`
```suggestion
#### Change this to publish this server, set genre, location and other parameters. It is recommended to override this file via `systemctl edit jamulus-headless.service`
```

2021-03-17 10:26 UTC, softins commented
> That way, users could just put the relevant `Environment=` lines in their overrides and don't have to copy/modify the `ExecStart` line.

I do something along similar lines for the RPMs I build for CentOS and Amazon Linux. The service file contains this:
```
[Service]
EnvironmentFile=-/etc/sysconfig/jamulus
...
# Do not edit this command. Edit /etc/sysconfig/jamulus instead.
ExecStart=/bin/sh -c 'exec /usr/sbin/jamulusd --server --nogui --fastupdate $${OPTS} \
        --log "$${LOGFILE:-/var/log/jamulus/jamulus.log}" \
        $${MULTITHREADING:+--multithreading} \
        $${PORT:+--port "$$PORT"} \
        $${RECORDING:+--recording "$$RECORDING"} \
        $${CENTRALSERVER:+--centralserver "$$CENTRALSERVER"} \
        $${SERVERINFO:+--serverinfo "$$SERVERINFO"} \
        $${WELCOME:+--welcomemessage "$$WELCOME"} \
        --numchannels $${CHANNELS:-10}'
...
```

and then `/etc/sysconfig/jamulus` is marked as a configuration file in the RPM (so it won't get clobbered) and contains:
```
# Configuration options for the Jamulus server

# Uncomment only ONE of these to register the server as public.
# Leave commented out for a private server.

# Default server
#CENTRALSERVER=jamulus.fischvolk.de:22124

# All Genres
#CENTRALSERVER=jamulusallgenres.fischvolk.de:22224

# Genre Rock
#CENTRALSERVER=jamulusrock.fischvolk.de:22424

# Genre Jazz
#CENTRALSERVER=jamulusjazz.fischvolk.de:22324
CENTRALSERVER=jazz.jamulus.io:22324

# Genre Classical/Folk/Choir
#CENTRALSERVER=jamulusclassical.fischvolk.de:22524

#CENTRALSERVER=worldjam.vip:22124

# Set this server name, city and country code (see below).
# Only needed for a public server.
#SERVERINFO="ChangeThisServerName;MyCity;224"
SERVERINFO="jamminthejazz;London AWS;224"

# The port to listen on (default is 22124)
PORT=22123

# The welcome message, which will be displayed in the chat window.
# HTML markup can be used.
WELCOME="<h2>Welcome to jamminthejazz</h2><p>This 3.7.0rc2 server is hosted on AWS in London and is run by Tony Mountifield in Winchester (tony@mountifield.org). Max channels 10.</p>"

# The maximum number of clients allowed to connect at once
CHANNELS=10

# Uncomment to enable multithreading on the server
# MULTITHREADING=yes

# If not specified, logfile will default to this.
LOGFILE=/var/log/jamulus/jamulus.log

# Uncomment to enable recording and specify directory
#RECORDING=/var/spool/jamulus

# Extra options to the server
#OPTS=""

# List of valid country codes (from QT)
#
#   0: Not specified
#   1: Afghanistan
#   2: Albania
...
```

2021-03-17 18:20 UTC, pljones commented
I run about 10 instances of Jamulus on my server.  They use this service _template_:
```
[Unit]
Description=Jamulus Server %i
Documentation=http://jamulus.drealm.info/jamulus
Documentation=https://jamulus.io/wiki/Server-Troubleshooting
After=network-online.target
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=20
IOSchedulingClass=realtime
IOSchedulingPriority=3
SyslogIdentifier=Jamulus-%i
StandardOutput=syslog
StandardError=syslog
User=Jamulus
Group=Jamulus
WorkingDirectory=~
Environment=UNIT=%i
EnvironmentFile=/opt/Jamulus/systemd/Jamulus.env
EnvironmentFile=/opt/Jamulus/systemd/%i.env
ExecStart=/opt/Jamulus/bin/run-Jamulus-template.sh
```
`Environment=UNIT=%i` lets me customise per instance...
`EnvironmentFile=/opt/Jamulus/systemd/Jamulus.env` pulls in my "standard environment", which is pretty empty:
```
# Where everything is
JAMULUS=Jamulus
JAMULUS_ROOT=/opt/Jamulus
JAMULUS_BINDIR=/opt/Jamulus/bin

# Actual defaults
JAMULUS_FASTUPDATE=true
JAMULUS_MULTITHREADED=false
JAMULUS_MAXCHANS=
JAMULUS_PUBLICIP=
JAMULUS_PORT=
JAMULUS_CENTRAL=
JAMULUS_FILTER=
JAMULUS_STATUSPAGE=
JAMULUS_SERVERNAME=
JAMULUS_LOGFILE=
JAMULUS_ENABLE_RECORDING=false
JAMULUS_RECORDING_DIR=
JAMULUS_SERVERINFO=
JAMULUS_WELCOMEMSG=
```
`EnvironmentFile=/opt/Jamulus/systemd/%i.env` is the customisation to the above, for example:
```
#JAMULUS_FASTUPDATE=true
#JAMULUS_MULTITHREADED=false
JAMULUS_MAXCHANS=1
#JAMULUS_PUBLICIP=
JAMULUS_PORT=22124
JAMULUS_CENTRAL=localhost
JAMULUS_FILTER=[3.6.1]
#JAMULUS_STATUSPAGE=
#JAMULUS_SERVERNAME='Jamulus-Central 1'
JAMULUS_LOGFILE=/opt/Jamulus/log/Central1.log
#JAMULUS_ENABLE_RECORDING=false
#JAMULUS_RECORDING_DIR=
JAMULUS_SERVERINFO='Central Server List (22124);London;224'
JAMULUS_WELCOMEMSG='<h3>Central Server List (22124)</h3><p>Genre-specific server list hosted by drealm.info.</p>'
```
`ExecStart=/opt/Jamulus/bin/run-Jamulus-template.sh` then does exactly the same thing for each one... but with lots of variable substitution.
```
#!/bin/bash -e
export LANG=C PATH="/usr/bin:/bin:$JAMULUS_BINDIR"
DAEMON="$JAMULUS_BINDIR/${JAMULUS}-${UNIT}"
if [ ! -x "$DAEMON" ] ; then
        echo "$DAEMON not installed." >&2
        exit 1
fi

JAMULUS_OPTS=("-s" "-n")
if [ ! -z "$JAMULUS_FASTUPDATE" ] && $JAMULUS_FASTUPDATE; then JAMULUS_OPTS+=("-F"); fi
if [ ! -z "$JAMULUS_MULTITHREADED" ] && $JAMULUS_MULTITHREADED; then JAMULUS_OPTS+=("-T"); fi
if [ ! -z "$JAMULUS_MAXCHANS" ] ; then JAMULUS_OPTS+=("-u" $JAMULUS_MAXCHANS); fi

if [ ! -z "$JAMULUS_PUBLICIP" ] ; then JAMULUS_OPTS+=("--serverpublicip" "$JAMULUS_PUBLICIP"); fi
if [ ! -z "$JAMULUS_PORT" ] ; then JAMULUS_OPTS+=("-p" $JAMULUS_PORT); fi
if [ ! -z "$JAMULUS_CENTRAL" ] ; then JAMULUS_OPTS+=("-e" "$JAMULUS_CENTRAL"); fi
if [ ! -z "$JAMULUS_FILTER" ] ; then JAMULUS_OPTS+=("-f" "$JAMULUS_FILTER"); fi

if [ ! -z "$JAMULUS_STATUSPAGE" -a -z "$JAMULUS_SERVERNAME" ] ; then
        echo "if STATUSPAGE set, SERVERNAME must be set" >&2
        exit 1
fi
if [ ! -z "$JAMULUS_STATUSPAGE" ] ; then JAMULUS_OPTS+=("-m" "$JAMULUS_STATUSPAGE"); fi
if [ ! -z "$JAMULUS_LOGFILE" ] ; then JAMULUS_OPTS+=("-l" "$JAMULUS_LOGFILE"); fi

if [ ! -z "$JAMULUS_ENABLE_RECORDING" ] && $JAMULUS_ENABLE_RECORDING && [ ! -z "$JAMULUS_RECORDING_DIR" ]
then
        JAMULUS_OPTS+=("-L" "-R" "$JAMULUS_RECORDING_DIR")
fi

if [ ! -z "$JAMULUS_SERVERINFO" ] ; then JAMULUS_OPTS+=("-o" "$JAMULUS_SERVERINFO"); fi
if [ ! -z "$JAMULUS_WELCOMEMSG" ] ; then JAMULUS_OPTS+=("-w" "$JAMULUS_WELCOMEMSG"); fi

echo "Starting Jamulus server" ;#"$JAMULUS_SERVERNAME"
if [ ! -z "$JAMULUS_STATUSPAGE" -a -e "$JAMULUS_STATUSPAGE" ] ; then
        cat > "$JAMULUS_STATUSPAGE" << !EOF
$JAMULUS_SERVERNAME Jamulus server is starting.
!EOF
fi

echo exec ${DAEMON} "${JAMULUS_OPTS[@]}"
exec ${DAEMON} "${JAMULUS_OPTS[@]}"
```

2021-03-23 18:39 UTC, closed without merging

2021-03-23 18:40 UTC, ann0see commented
I think we should open a discussion with the scripts published here and then descide what to include?