linux/sound: Fix HTML/C++ quoting
jamulussoftware/jamulus pull request #1439
Opened 2021-04-03 09:39 UTC by hoffie

As spotted by @passing in https://github.com/jamulussoftware/jamulus/pull/1127#discussion_r606487013.
    
Also update translation texts to avoid unnecessary work by translators.

2021-04-03 13:09 UTC, pljones approved these changes

2021-04-05 18:50 UTC, ann0see requested changes
Thanks! Please see my comments.

2021-04-05 18:50 UTC, ann0see commented on linux/sound.cpp
> +            "use a tool like <i><a href=\"http://qjackctl.sourceforge.net\">QJackCtl</a></i> "
```suggestion
            "use a tool like <i><a href=\"https://qjackctl.sourceforge.io\">QJackCtl</a></i> "
```

They're using https now.

2021-04-05 18:50 UTC, ann0see commented on src/res/translation/translation_de_DE.ts
> +        <translation>Do kannst ein Werkzeug wie &lt;i&gt;&lt;a href=&quot;http://qjackctl.sourceforge.net&quot;&gt;QJackCtl&lt;/a&gt;&lt;/li&gt; verwenden um die Samplerate umzustellen.</translation>
```suggestion
        <translation>Du kannst ein Werkzeug wie &lt;i&gt;&lt;a href=&quot;http://qjackctl.sourceforge.net&quot;&gt;QJackCtl&lt;/a&gt;&lt;/li&gt; verwenden um die Samplerate umzustellen.</translation>
```

2021-04-05 19:21 UTC, hoffie commented
@ann0see Thanks for the hints. I fixed this in separate commits as the fixes are unrelated to the original issue. Therefore, please don't squash-merge. :)

2021-04-05 19:26 UTC, ann0see commented
Argh. Sorry I didn't make it clear enough: it's https://\*.sourceforge.**io** if you use https not https://\*.sourceforge.**net**

2021-04-05 20:34 UTC, hoffie commented
> Argh. Sorry I didn't make it clear enough: it's https://*.sourceforge.**io** if you use https not https://*.sourceforge.**net**

Ah, I had missed this. Should have checked more thoroughly. Should be fixed now.

2021-04-06 07:39 UTC, ann0see approved these changes
Great

2021-04-06 07:40 UTC, merged

2021-04-06 07:40 UTC, ann0see commented
Thanks!