Prevent illegal server info from GUI
jamulussoftware/jamulus pull request #1804
Opened 2021-06-01 07:56 UTC by pljones

2021-06-04 10:06 UTC, softins requested changes
Comments made from reading, without trying to compile and execute.

2021-06-04 10:06 UTC, softins commented on src/settings.h
> +    CServerSettings ( CServer* pNSerP, const QString& sNFiName ) : CSettings(), pServer ( pNSerP ), reSvrInfoIllegal ( QRegExp ( "[!\n;]" ) )
See comment above for `serverdlg.cpp`. I realise this particular RE is only used for `QString::remove()`, which would imply you do actually intend to remove `!` characters too. (?)

2021-06-04 17:36 UTC, ann0see reviewed
Was this PR raised to remain consistent with the CLI (which doesn't support \n and ;) or is it because these characters are problematic in any other way?

2021-06-04 17:36 UTC, ann0see commented on src/serverdlg.cpp
> +    reSvrInfoIllegal ( QRegExp ( "[!;\n]*" ) )
! does't seem to be an invalid character (at least I doubt it's a problem). Waiting on @pljones

2021-06-05 09:14 UTC, pljones commented on src/serverdlg.cpp
> +    reSvrInfoIllegal ( QRegExp ( "[!;\n]*" ) )
Should be "^" at tge start.

2021-06-05 11:14 UTC, pljones commented
Hopefully it should be a lot better today.

(I tested this one, too...)

2021-06-12 22:10 UTC, pljones commented
Going with a different approach, so this solution isn't needed.

2021-06-12 22:10 UTC, closed without merging