Update fr_FR app translation for 3.8.2
jamulussoftware/jamulus pull request #2320
Opened 2022-01-28 23:47 UTC by jujudusud

**Short description of changes**
Update fr_FR app translation for 3.8.2

**Context: Fixes an issue?**
Fixes #2303

**Does this change need documentation? What needs to be documented and how?**
No

**Status of this Pull Request**
Ready to be merged into master.

2022-01-29 07:27 UTC, hoffie commented on src/res/translation/translation_fr_FR.ts
> +        <translation>256 échantillons : Devrait être utilisé uniquement si le réglage 64 ou 128 échantillons provoque des disfonctionnements.</translation>
```suggestion
        <translation>256 échantillons: Devrait être utilisé uniquement si le réglage 64 ou 128 échantillons provoque des disfonctionnements.</translation>
```
Redundant space before `:`?

2022-01-29 07:32 UTC, hoffie approved these changes
Looks fine to me, thanks! :)

- [x] Translator listed in the src/util.cpp, optionally add link to PR or code
- [x] Punctuation and spacing consistent.
- [x] Signal words consistent (“ASIO”, “Buffer”)
- [x] App translations: No untranslated strings (grep unfinished -5 src/res/translation/translation_$TRANSLATION*.ts)
- [x] App translations: Only a single .ts file checked in (.qm in addition is also OK)
- [x] Installer translations: Passes tools/check-wininstaller-translations.sh

2022-01-29 08:04 UTC, trebmuh requested changes
Pas eu le temps de tout relire, mais voici 3 commentaires.
Sinon, le reste me semble très bien, bravo.

2022-01-29 08:04 UTC, trebmuh commented on src/res/translation/translation_fr_FR.ts
> +        <translation>Un serveur collecte les données audio de chaque client, les mixes et renvoie le résultat à chaque client.</translation>
A la question "qui mixe les données ?", la réponse est "le serveur", c'est dont une 3ème personne de l'indicatif présent, donc "mixe" (pas de s final)

2022-01-29 08:04 UTC, trebmuh commented on src/res/translation/translation_fr_FR.ts
> +        <translation>A propos %1</translation>
À, pas A

2022-01-29 08:04 UTC, trebmuh commented on src/res/translation/translation_fr_FR.ts
> +        <translation>%1 Annuaire</translation>
Réflexion : ce n'est pas "directory" au sens de "répertoire" par hasard ?

2022-01-31 18:48 UTC, ann0see reviewed
Waiting until comments by trebmuh are resolved

2022-01-31 22:51 UTC, jujudusud commented on src/res/translation/translation_fr_FR.ts
> +        <translation>Un serveur collecte les données audio de chaque client, les mixes et renvoie le résultat à chaque client.</translation>
ok dans 965b2d3

2022-01-31 22:51 UTC, jujudusud commented on src/res/translation/translation_fr_FR.ts
> +        <translation>A propos %1</translation>
ok dans 965b2d3

2022-01-31 22:52 UTC, jujudusud commented on src/res/translation/translation_fr_FR.ts
> +        <translation>%1 Annuaire</translation>
ok dans 965b2d3

2022-01-31 22:53 UTC, jujudusud commented
> Waiting until comments by trebmuh are resolved

Done with 965b2d3

2022-01-31 23:07 UTC, hoffie approved these changes

2022-02-01 06:17 UTC, ann0see approved these changes

2022-02-01 06:17 UTC, merged