Update opus to 1.5.2
jamulussoftware/jamulus pull request #3409
Opened 2024-10-12 17:14 UTC by softins

**Short description of changes**

Update Opus library to the latest 1.5.2 release, plus a couple of fixes.

CHANGELOG: Update Opus library to v1.5.2

**Context: Fixes an issue?**

Existing Jamulus is using V1.4 of Opus. There are improvements to V1.5.2, which may enhance audio quality in some situations. It's just good to be on a current version. This was based on the distribution tarball for V1.5.2, not on a gitlab checkout, which would require an extra configuration step before use.

A couple of extra fixes were added, one a backport of a fix for a segfault, and two to silence compiler warnings.

**Does this change need documentation? What needs to be documented and how?**
Probably not, as it's just internal.

**Status of this Pull Request**
Ready for review. Tested on Linux server and Mac client. Hard to tell if the audio is slightly improved, but it's certainly not worse.

**What is missing until this pull request can be merged?**
Review. Testing on other platforms.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [ ] I've filled all the content above

2024-10-12 21:26 UTC, ann0see commented
Thanks.

Did you report the compiler errors to upstream too?

2024-10-12 21:58 UTC, softins commented
> Thanks.
> 
> Did you report the compiler warnings to upstream too?

Not yet, I wanted to see if they had been fixed in any branches first. But I intend to.

2024-10-14 19:25 UTC, ann0see requested changes

2024-10-14 19:25 UTC, ann0see commented on Jamulus.pro
Compiling on Debian with Qt 5 gives the following warning:

```
WARNING: Failure to find: libs/opus/src/tansig_table.h
```

I believe, you'll need to remove tansig_table.h

2024-10-14 19:29 UTC, ann0see commented
Otherwise, works on Debian 12 (client)

2024-10-16 14:33 UTC, softins commented on Jamulus.pro
Looks like that include file no longer exists in Opus 1.5.2, so I'll just remove it from `Jamulus.pro`

2024-10-16 14:58 UTC, ann0see commented on Jamulus.pro
Thanks.

2024-10-16 14:58 UTC, ann0see approved these changes

2024-10-31 21:39 UTC, ann0see commented
@pljones @gilgongo Could you please also test this?

2024-11-01 19:31 UTC, pljones commented
Jack on Windows has decided it's going to crash for me at the moment (it goes through phases).  No audio on my Linux box (and, as Jack on Windows crashes, I can't use Jack Net to send the audio over to Windows, either).  Audio out on Windows is okay.

2024-11-01 19:33 UTC, pljones approved these changes
Didn't crash (JACK and ASIO on Windows).  ASIO audio out was fine.

2024-11-01 22:23 UTC, merged