Translations update from Hosted Weblate
jamulussoftware/jamulus pull request #3453
Opened 2024-12-29 13:26 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Jamulus/Jamulus app](https://hosted.weblate.org/projects/jamulus/jamulus-app/).

It also includes following components:

* [Jamulus/Windows Installer](https://hosted.weblate.org/projects/jamulus/windows-installer/)

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widget/jamulus/jamulus-app/horizontal-auto.svg)

2025-03-22 19:56 UTC, ann0see approved these changes
I can't check everything (esp. ko_KR), but de is fine.

2025-08-03 08:41 UTC, ann0see commented on src/translation/translation_pt_PT.ts
> +        <translation>VersãoEtiquetaTexto</translation>
Probably, this should not be translated.

2025-08-03 09:00 UTC, pljones commented
Several languages have "version" as "version" -- is that right?  And Brazilian has had some word that looked like it was probably appropriate changed to "framework" as a translation of "framework".  Obviously, if common usage has these as correct, that's okay.  But I can't check.

2025-08-03 09:07 UTC, ann0see commented
In German, it's the same word. But for the other languages, I also have no clue.

2025-09-02 18:18 UTC, pljones approved these changes

2025-09-14 16:43 UTC, ann0see requested changes
Almost ok

2025-09-14 16:43 UTC, ann0see commented on src/translation/translation_pl_PL.ts
> +        <translation>Sortuj użytkowników po kanale</translation>
Probably not correct: the &amp is needed.

2025-09-14 16:43 UTC, ann0see commented on src/translation/translation_pt_PT.ts
> +        <translation>VersãoEtiquetaTexto</translation>
Todo!!

2025-09-14 16:56 UTC, ann0see approved these changes

2025-09-14 16:56 UTC, merged