Add the Mute Stream shortcut for simple control.
jamulussoftware/jamulus pull request #942
Opened 2021-02-02 19:06 UTC by jardous

This simple change allows controlling the mute easily by pressing the M key on the keyboard (when the main window has focus).

The motivation is to use a modified keyboard (with just the M key) as a control pedal to easily mute/unmute myself between listening/playing.

2021-02-02 19:31 UTC, ann0see approved these changes
I hope there isn't any other feature which uses the m shortcut.

2021-02-02 20:14 UTC, jardous commented
> I hope there isn't any other feature which uses the m shortcut.
Currently this looks like it is the only shortcut used in the whole project

2021-02-03 06:44 UTC, ann0see commented
I thought there were some more what happens if you use CTRL+S or CTRL+M?

2021-02-03 08:04 UTC, jardous commented
> I thought there were some more what happens if you use CTRL+S or CTRL+M?

Nothing. Those are not defined at all. 
It will however break the "ALT+M" accelerator that is defined in the string "<string>&amp;Mute Myself</string>" and it depends on loaded translation.

2021-02-03 11:14 UTC, ann0see requested changes
Ah. So it was "ALT+M". Can we somehow improve this to still allow the alt+m shortcut?

2021-02-06 23:41 UTC, pljones commented
If we're going to start having shortcuts like this, I think there's going to be a need to have the ability to disable/enable them in settings / menu option.  I don't mind accelerator keys - Alt-M, etc - as I have control (well, Alt) over them.  Suddenly finding the M key does something might be inconvenient...

2021-02-07 07:23 UTC, ann0see commented
@jardous Although I like this feature, would it be possible for your modified keyboard to send alt+m? This feature shouldn't break another one.

2021-02-07 08:02 UTC, jardous commented
with a custom keyboard it would be possible. Let's reject this for now.

2021-02-07 08:10 UTC, ann0see commented
Ok. So I'll close this.

2021-02-07 08:10 UTC, closed without merging