Add compilation support for nsProcess
jamulussoftware/jamulus pull request #962
Opened 2021-02-06 21:05 UTC by ann0see

Fixes #859

2021-02-10 19:46 UTC, pljones requested changes

2021-02-10 20:48 UTC, ann0see commented on windows/nsProcess/api.h
> + * Licence details can be found in the file COPYING.
Good question...

2021-02-10 20:48 UTC, ann0see commented on windows/nsProcess/README_JamulusChanges.txt
> +we compile the source code of the NSIS Plugin. Unfortunately it seems to be quite old. That's why I (@ann0see) updated it on 2020-02-06 to support compilation
Fixed.

2021-02-10 20:49 UTC, ann0see commented on windows/nsProcess/api.h
> + * Licence details can be found in the file COPYING.
Maybe here: https://github.com/kichik/nsis/blob/master/COPYING

2021-02-10 22:01 UTC, pljones commented on windows/nsProcess/api.h
> + * Licence details can be found in the file COPYING.
Probably needs a specific link or including.

2021-02-10 22:02 UTC, ann0see commented on windows/nsProcess/api.h
> + * Licence details can be found in the file COPYING.
I hope this is the correct file. But I think so.

2021-02-11 07:58 UTC, ann0see commented on windows/nsProcess/api.h
> + * Licence details can be found in the file COPYING.
I think this is the correct one: https://sourceforge.net/p/nsis/code/HEAD/tree/NSIS/trunk/COPYING

2021-02-11 08:25 UTC, ann0see commented on windows/nsProcess/api.h
> + * Licence details can be found in the file COPYING.
Ok. Added the file now.

2021-02-11 12:18 UTC, ann0see commented
@nefarius2001 I assume, you'll need to include this PR in your PR too.

2021-02-11 12:39 UTC, pljones approved these changes

2021-02-17 19:37 UTC, pljones approved these changes

2021-02-17 19:39 UTC, pljones commented
@softins any comments on this one?  Else @ann0see, do you want to approve and merge for 3.7.0?

2021-02-17 19:40 UTC, ann0see commented
Probably we could merge this, but it's already included nefarius PR.

2021-02-17 19:40 UTC, ann0see commented
Unfortunately, I can't approve it myself.

2021-02-17 19:44 UTC, softins commented
I don't know enough about this module to comment knowledgeably. I assume the CI compiles it ok, and that it has been tested out on a Windows machine. Happy to approve if so.

2021-02-17 19:51 UTC, ann0see commented
Yes. It compiles on Windows and also on GH Actions. I'm not responsible for all the deprecation warnings from this code. If we have time, we might fix them (but the code is not Jamulus related)

2021-02-17 19:59 UTC, pljones commented
> 
> 
> Probably we could merge this, but it's already included nefarius PR.

Ah - @nefarius2001 can this be closed then?

2021-02-17 21:22 UTC, nefarius2001 commented
Sort of - I'd suggest closing when  #978 is merged

2021-02-18 21:16 UTC, merged