Update ChangeLog
jamulussoftware/jamulus pull request #979
Opened 2021-02-10 22:15 UTC by dcorson-ticino-com

feature-req925 recording indicator (#968)

2021-02-10 22:29 UTC, ann0see approved these changes
Thanks!

2021-02-10 22:38 UTC, trebmuh commented on ChangeLog
> +- Highlite the fact that the server is recording in the Mixerboard title (#968), coded by dcorson-ticino.com
Shouldn't that be "Highlight" ?

2021-02-12 06:45 UTC, ann0see requested changes
Could you please apply this typo fix?

2021-02-12 08:29 UTC, ann0see approved these changes
Thanks!

2021-02-12 18:13 UTC, pljones approved these changes

2021-02-12 18:14 UTC, merged